# -*- coding: utf-8 -*-
"""RAG + Finetuned Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EySCwMnldzZFXB4zuhJvebwRSQHWycoT

#Combining all Dataset
"""

import pandas as pd
import re

# Updated paths to all datasets (all are now CSV)
paths = [
   "/content/2-limitation-act-1908-pdf_extracted.csv",
    "/content/Code_of_Criminal_Procedure_Structured upto 16 chapter.csv",
    "/content/Muslim_Family_Laws_Ordinance_1961.csv",
    "/content/Pakistan_Penal_Code.csv",
    "/content/Police_law.csv",
    "/content/Transfer property.csv",
    "/content/qanun-e-shahadat_1984.csv"
]

# Define the text cleaning function
def clean_text(text):
    if pd.isna(text):
        return ""
    text = re.sub(r'\s+', ' ', str(text))  # remove extra whitespaces
    text = text.replace('\xa0', ' ')       # fix non-breaking space
    return text.strip()

# Columns we care about
required_columns = ['Book', 'Chapter Number', 'Chapter Title', 'Section', 'Heading', 'Defination']

# Load and clean all datasets
cleaned_dfs = []
for path in paths:
    df = pd.read_csv(path, encoding='ISO-8859-1')
    df = df[[col for col in required_columns if col in df.columns]]

    # Ensure all required columns are present
    for col in required_columns:
        if col not in df.columns:
            df[col] = ""

    for col in required_columns:
        df[col] = df[col].apply(clean_text)

    cleaned_dfs.append(df[required_columns])

# Combine all into one DataFrame
final_combined_df = pd.concat(cleaned_dfs, ignore_index=True)

# import ace_tools as tools; tools.display_dataframe_to_user(name="Final Combined Legal Dataset", dataframe=final_combined_df)

final_combined_df.to_csv("final_combined_legal_dataset.csv", index=False)

final_combined_df.head(5)

"""**Adding Developer info**"""

# Step 1: Add developer info
developer_info = {
    "Book": "Chatbot Info",
    "Chapter Number": "0",
    "Chapter Title": "Developers",
    "Section": "001",
    "Heading": "Creators of this Legal Chatbot",
    "Defination": "This legal chatbot was created by Umair Ahmed, Ritika Rani, and Gungun Sadhwani, "
                  "undergraduate students of the Computer Science department at Sukkur IBA University."
}

# Step 2: Add identity-related query triggers
identity_queries = [
    "Who created this chatbot?",
    "Who built you?",
    "Who are your developers?",
    "Tell me your creators' names.",
    "Who designed this legal assistant?",
    "Who made you?",
    "Who is behind this chatbot?",
    "Who developed you?",
    "Tell me about your development team.",
    "What’s the name of your makers?",
    "Which university made you?",
    "What’s the background of your developers?",
    "Who is Umair Ahmed?",
    "Are you developed by Sukkur IBA University students?",
    "Are you a student project?",
    "Who are Ritika Rani and Gungun Sadhwani?",
    "Did computer science students make you?",
    "Who is your owner?",
    "Can you tell me who coded you?",
    "Who trained you on Pakistani law?"
]

identity_rows = [{
    "Book": "Chatbot Info",
    "Chapter Number": "0",
    "Chapter Title": "Developer Queries",
    "Section": f"Q{i+1:03}",
    "Heading": q,
    "Defination": developer_info["Defination"]
} for i, q in enumerate(identity_queries)]

# Add to the final DataFrame
final_combined_df = pd.concat(
    [final_combined_df, pd.DataFrame([developer_info]), pd.DataFrame(identity_rows)],
    ignore_index=True
)

# Show updated dataset
# import ace_tools as tools; tools.display_dataframe_to_user(name="Dataset with Developer Info", dataframe=final_combined_df)

final_combined_df.head(5)

final_combined_df.to_csv("final_combined_legal_dataset_with_dev_info.csv", index=False)

final_combined_df['Heading'][1408]



"""#Started RAG"""

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pandas as pd

# Reload your final dataset
final_df = pd.read_csv("/content/final_combined_legal_dataset_with_dev_info.csv")

# Combine fields into a single text column
final_df["text"] = (
    "Book: " + final_df["Book"].astype(str) + " | " +
    "Chapter: " + final_df["Chapter Number"].astype(str) + " - " + final_df["Chapter Title"].astype(str) + " | " +
    "Section: " + final_df["Section"].astype(str) + " - " + final_df["Heading"].astype(str) + "\n" +
    final_df["Defination"].astype(str)
)

# Generate embeddings
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

# Generate embeddings
# model = SentenceTransformer("BAAI/bge-base-en-v1.5")
texts = final_df["text"].tolist()
embeddings = model.encode(texts, show_progress_bar=True)
embeddings = np.array(embeddings).astype("float32")
faiss.normalize_L2(embeddings)

# Create FAISS index
dimension = embeddings.shape[1]
faiss_index = faiss.IndexFlatIP(dimension)
faiss_index.add(embeddings)

# Save index + metadata
faiss.write_index(faiss_index, "legal_faiss_index.index")
final_df.to_csv("legal_faiss_metadata.csv", index=False)

!pip install -q sentence-transformers faiss-cpu

import pandas as pd
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

# Load metadata and FAISS index
metadata_df = pd.read_csv("/content/legal_faiss_metadata.csv")
index = faiss.read_index("/content/legal_faiss_index.index")
# model = SentenceTransformer("BAAI/bge-base-en-v1.5")

# Define search function
def search_legal_context(query, k=5):
    query_vector = model.encode([query])
    query_vector = np.array(query_vector).astype("float32")
    faiss.normalize_L2(query_vector)
    scores, indices = index.search(query_vector, k)
    results = metadata_df.iloc[indices[0]]
    return results[["Section", "Heading", "Defination"]]

# Example Query
search_legal_context("How to file FIR in Pakistan?", k=3)

"""#Vector DB through Langchain"""

pip install -U langchain-community

from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.document_loaders import CSVLoader
from langchain.text_splitter import CharacterTextSplitter

# Step 1: Load and chunk documents
loader = CSVLoader("/content/final_combined_legal_dataset_with_dev_info.csv")
docs = loader.load()

splitter = CharacterTextSplitter(chunk_size=512, chunk_overlap=50)
docs_split = splitter.split_documents(docs)

# Step 2: Embed and build FAISS
embedding = HuggingFaceEmbeddings(model_name="BAAI/bge-base-en-v1.5")
db = FAISS.from_documents(docs_split, embedding)

# Step 3: Retrieve chunks (you write this part)
def retrieve_context(query, k=5):
    return db.similarity_search(query, k=k)

# Step 4: Build prompt with context
context_docs = retrieve_context("What is limitation for filing appeal?")
context = "\n\n".join([doc.page_content for doc in context_docs])

final_prompt = f"""Context:
{context}

Question:
What is limitation for filing appeal?

Answer:"""

# Step 5: Call your finetuned model on this prompt
# output = generate_response(final_prompt)

print(context)

db

"""**saving the FAISS database local**"""

db.save_local("faiss_legal_db")

"""**Loading FAISS**"""

from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings

# embedding = HuggingFaceEmbed`dings(model_name="BAAI/bge-base-en-v1.5")
# db = FAISS.load_local("faiss_legal_db", embeddings=embedding)

# Add allow_dangerous_deserialization=True to enable loading
db = FAISS.load_local("faiss_legal_db", embeddings=embedding, allow_dangerous_deserialization=True)

# print(db.similarity_search("What is limitation for filing appeal?", k=5))

def retrieve_context(query, k=5):
    return db.similarity_search(query, k=k)

# Step 4: Build prompt with context
context_docs = retrieve_context("What is limitation for filing appeal?")
context = "\n\n".join([doc.page_content for doc in context_docs])
print(context)



"""##Downloading FAISS database through langchian"""

import shutil
from google.colab import files

# Step 1: Zip the entire FAISS DB folder
shutil.make_archive("faiss_legal_db", 'zip', "faiss_legal_db")

# Step 2: Download the zip file
files.download("faiss_legal_db.zip")

docs_split[2]

# Initialize BM25 Retriever
bm25_retriever = BM25Retriever.from_documents(docs_split)

"""#Creating BM25 Retriever"""

pip install rank_bm25

from langchain.retrievers import BM25Retriever
# Initialize BM25 Retriever
bm25_retriever = BM25Retriever.from_documents(docs_split)

def retrieve_combined_context(query, k_faiss=3, k_bm25=3):
    # Get top-k results from both
    faiss_results = db.similarity_search(query, k=k_faiss)
    bm25_results = bm25_retriever.get_relevant_documents(query)[:k_bm25]

    # Combine content from both
    faiss_context = "\n\n".join([doc.page_content for doc in faiss_results])
    bm25_context = "\n\n".join([doc.page_content for doc in bm25_results])

    # Merge both contexts
    final_context = f"FAISS Context:\n{faiss_context}\n\nBM25 Context:\n{bm25_context}"
    return final_context

query = "How to file FIR in Pakistan?"
context = retrieve_combined_context(query)

final_prompt = f"""Context:
{context}

Question:
{query}

Answer:"""

print(context)

import pickle

# Save the documents used to create the BM25 retriever
with open("bm25_docs.pkl", "wb") as f:
    pickle.dump(docs_split, f)

from google.colab import files
files.download("bm25_docs.pkl")

"""**Load like this**"""

import pickle
from langchain.retrievers import BM25Retriever

# Load saved docs
with open("bm25_docs.pkl", "rb") as f:
    docs_split = pickle.load(f)

# Rebuild the retriever
bm25_retriever = BM25Retriever.from_documents(docs_split)

"""#Performance Matrix on Complete RAG + fine tuned model

##**Loading Model**
"""

from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("heyIamUmair/llama3-3b-merged-legal", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("heyIamUmair/llama3-3b-merged-legal")

prompt = "### Question:\nWhat is talaq under Pakistani law?\n\n### Answer:\n"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=150)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""##Loading Vector Databases"""

!pip install -q langchain-community sentence-transformers faiss-cpu rank_bm25

import zipfile
import pickle
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.retrievers import BM25Retriever

"""##Hybrid Vector Database

###Unzip Load Faiss
"""

# Unzip FAISS DB
with zipfile.ZipFile("/content/faiss_legal_db.zip", 'r') as zip_ref:
    zip_ref.extractall("faiss_legal_db")

# Load FAISS
embedding = HuggingFaceEmbeddings(model_name="BAAI/bge-base-en-v1.5")
faiss_db = FAISS.load_local("faiss_legal_db", embeddings=embedding, allow_dangerous_deserialization=True)

"""###Load BM25"""

# Load BM25 retriever docs
with open("/content/bm25_docs.pkl", "rb") as f:
    docs_split = pickle.load(f)

bm25_retriever = BM25Retriever.from_documents(docs_split)

"""##Retriving Context"""

# Define combined context retriever
def retrieve_combined_context(query, k_faiss=3, k_bm25=3):
    faiss_results = faiss_db.similarity_search(query, k=k_faiss)
    bm25_results = bm25_retriever.get_relevant_documents(query)[:k_bm25]

    faiss_context = "\n\n".join([doc.page_content for doc in faiss_results])
    bm25_context = "\n\n".join([doc.page_content for doc in bm25_results])

    final_context = f"FAISS Context:\n{faiss_context}\n\nBM25 Context:\n{bm25_context}"
    return final_context

# Test it
print(retrieve_combined_context("How to file FIR in Pakistan?", k_faiss=3, k_bm25=3))

# Test it
print(retrieve_combined_context("What is the punishment for theft in pakista", k_faiss=3, k_bm25=3))

# Test it
print(retrieve_combined_context("Who is your developer", k_faiss=3, k_bm25=3))

# Test it
print(retrieve_combined_context("What is the punishment for murder", k_faiss=3, k_bm25=3))

# Test it
print(retrieve_combined_context("if someone falsy file fir on me What should I do?", k_faiss=3, k_bm25=3))

"""##**Using with model**"""

def retrieve_combined_context(query, k_faiss=3, k_bm25=3):
    faiss_results = faiss_db.similarity_search(query, k=k_faiss)
    # bm25_results = bm25_retriever.get_relevant_documents(query)[:k_bm25]

    faiss_context = "\n\n".join([doc.page_content for doc in faiss_results])
    # bm25_context = "\n\n".join([doc.page_content for doc in bm25_results])

    # return f"FAISS Context:\n{faiss_context}\n\nBM25 Context:\n{bm25_context}"
    return f"FAISS Context:\n{faiss_context}"

# def build_rag_prompt(query):
#     context = retrieve_combined_context(query)
#     return f"""<|user|>
# Use the following context to answer the question. Be clear and mention relevant sections.

# Context:
# {context}

# Question:
# {query}

# <|assistant|>
# """

# return f"""<|user|>
# You are a helpful Pakistani legal assistant. Use the following legal context to answer the user's question **in clear, simple language**.

# ✅ Format your answer in **Markdown**.
# ✅ Provide relevant citations such as:
# - 📘 *Book Name*
# - 🔖 *Section Number*
# - 📄 *Section Heading*

# If no relevant information is found, say "**I'm sorry, I couldn't find a specific law related to this.**"

# ---

# ### 📚 Legal Context
# {context}

# ---

# ### ❓ User's Question
# {query}

# ---

# ### 🧾 Answer
# <|assistant|>
# """



def build_rag_prompt(query):
    context = retrieve_combined_context(query)

    return f"""<|user|>
You are a helpful Pakistani legal assistant. Use the following legal context to answer the user's question **in clear, simple language**.

  Format your answer in **Markdown**.
 Provide relevant citations such as:
-  *Book Name*
-  *Section Number*
-  *Section Heading*

If no relevant information is found, say "**I'm sorry, I couldn't find a specific law related to this.**"

---

### Legal Context
{context}

---

### User's Question
{query}

---

### Answer
<|assistant|>
"""

from transformers import AutoModelForCausalLM, AutoTokenizer

# model = AutoModelForCausalLM.from_pretrained("heyIamUmair/llama3-3b-merged-legal", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("heyIamUmair/llama3-3b-merged-legal")

import torch

model = AutoModelForCausalLM.from_pretrained(
    "heyIamUmair/llama3-3b-merged-legal",
    torch_dtype=torch.float16,
    device_map="auto"
)

# import torch

# def generate_response_rag(prompt):

#     # model.to(inputs.device)

#     inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
#     outputs = model.generate(
#         **inputs,
#         max_new_tokens=150,
#     )
#     return tokenizer.decode(outputs[0], skip_special_tokens=True)

import torch

def generate_response_rag(prompt):
    # Ensure the tokenizer output is on the correct device before generating
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)  # Change here

    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

import torch
torch.cuda.empty_cache()

query = "How to file FIR in Pakistan?"
prompt = build_rag_prompt(query)
response = generate_response_rag(prompt)
print(response)

"""##Model using Langchain"""

from transformers import pipeline
from langchain.llms import HuggingFacePipeline

# Wrap Hugging Face generation pipeline
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=256,
    temperature=0.7,
    top_p=0.9,
    repetition_penalty=1.1,
    # device=0  # or "cuda"
)

llm = HuggingFacePipeline(pipeline=pipe)

from langchain.chains import RetrievalQA

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=faiss_db.as_retriever(),  # or your hybrid retriever
    chain_type="stuff"
)

# Full RAG query
response = qa_chain.run("How to file FIR in Pakistan?")
print(response)

response = qa_chain.run("what is punishment for theft")
print(response)

"""###Langchain Template + retreival + model"""

from langchain.prompts import PromptTemplate

rag_prompt = PromptTemplate(
    input_variables=["context", "question"],
    template="""<|user|>
You are a helpful Pakistani legal assistant. Use the following legal context to answer the user's question **in clear, simple language**.

✅ Format your answer in **Markdown**.
✅ Provide citations such as:
- 📘 Book Name
- 🔖 Section Number
- 📄 Section Heading

If no relevant law is found, say: **"I'm sorry, I couldn't find a specific law related to this."**

---

### 📚 Legal Context
{context}

---

### ❓ User's Question
{question}

---

### 🧾 Answer
<|assistant|>"""
)

def retrieve_combined_context(query, k_faiss=3, k_bm25=3):
    faiss_results = faiss_db.similarity_search(query, k=k_faiss)
    # bm25_results = bm25_retriever.get_relevant_documents(query)[:k_bm25]

    faiss_context = "\n\n".join([doc.page_content for doc in faiss_results])
    # bm25_context = "\n\n".join([doc.page_content for doc in bm25_results])

    # return f"FAISS Context:\n{faiss_context}\n\nBM25 Context:\n{bm25_context}"
    return f"FAISS Context:\n{faiss_context}"

from langchain.chains import LLMChain

rag_chain = LLMChain(
    llm=llm,  # HuggingFacePipeline-wrapped model
    prompt=rag_prompt
)

response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": query
})

print(response)

response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": "who created you"
})

print(response)

response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": "who is Umair Ahmed"
})

print(response)

def retrieve_combined_context(query, k_faiss=3, k_bm25=3):
    faiss_results = faiss_db.similarity_search(query, k=k_faiss)
    # bm25_results = bm25_retriever.get_relevant_documents(query)[:k_bm25]

    faiss_context = "\n\n".join([doc.page_content for doc in faiss_results])
    # bm25_context = "\n\n".join([doc.page_content for doc in bm25_results])

    # return f"FAISS Context:\n{faiss_context}\n\nBM25 Context:\n{bm25_context}"
    return f"FAISS Context:\n{faiss_context}"

response = retrieve_combined_context("who created you")

print(response)

query = "who is your developer"
response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": query
})

print(response)

query = "who made you"
response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": query
})

print(response)

query = "yesterday teacher slaped me infront of all student. now i am confused what should i do?"
response = rag_chain.run({
    "context": retrieve_combined_context(query),
    "question": query
})

print(response)

"""###function to extract only answer part"""

import re

def extract_markdown_answer(response_text):
    """
    Extracts clean text after '### 🧾 Answer' and '<|assistant|>' from a Markdown-styled response.
    """
    pattern = r"### 🧾 Answer\s*<\|assistant\|>\s*(.*)"
    match = re.search(pattern, response_text, re.DOTALL)
    return match.group(1).strip() if match else "No valid answer found."

clean_answer = extract_markdown_answer(response)
print(clean_answer)

# query = "yesterday teacher slaped me infront of all student. now i am confused what should i do?"

def get_answer_from_chatbot(query):
  response = rag_chain.run({
      "context": retrieve_combined_context(query),
      "question": query
  })
  # print(response)
  clean_answer = extract_markdown_answer(response)
  return clean_answer

print(get_answer_from_chatbot("yesterday teacher slaped me infront of all student. now i am confused what should i do?"))

print(get_answer_from_chatbot("who created you"))

print("cleaned answer: ",get_answer_from_chatbot("punishment for murder"))

print(get_answer_from_chatbot("who created you"))

"""#**Testing**"""

import pandas as pd

# Retry loading using the correct uploaded file path
df = pd.read_csv("/content/combined_30_legal_dataset.csv")

# Generate responses and append to new column
generated_answers = []
for query in df["Query"]:
    try:
      answer = get_answer_from_chatbot(query)
    except Exception as e:
        answer = f"Error: {e}"
    generated_answers.append(answer)

# Append to DataFrame
df["Generated_Response"] = generated_answers

# pd.to_csv(df, index=False)

df.head(5)

# ✅ Save updated DataFrame to CSV
df.to_csv("/content/combined_30_legal_dataset_with_generated_answers.csv", index=False)

"""##Performance metrix"""

import pandas as pd
df = pd.read_csv("/content/combined_30_legal_dataset_with_generated_answers.csv")

!pip install rouge-score nltk

from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.meteor_score import meteor_score
import nltk

# Ensure required resources are downloaded
nltk.download("wordnet")

# Initialize scorers
rouge = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

bleu_scores = []
meteor_scores = []
rouge_scores = []

# Evaluate each pair of ground truth and generated response
for ref, gen in zip(df["Response"], df["Generated_Response"]):
    if isinstance(ref, str) and isinstance(gen, str):
        bleu_scores.append(sentence_bleu([ref.split()], gen.split()))
        meteor_scores.append(meteor_score([ref.split()], gen.split()))
        rouge_scores.append(rouge.score(ref, gen))
    else:
        bleu_scores.append(0)
        meteor_scores.append(0)
        rouge_scores.append({
            "rouge1": rouge_scorer.Score(0, 0, 0),
            "rouge2": rouge_scorer.Score(0, 0, 0),
            "rougeL": rouge_scorer.Score(0, 0, 0)
        })

# Calculate averages
avg_bleu = sum(bleu_scores) / len(bleu_scores)
avg_meteor = sum(meteor_scores) / len(meteor_scores)
avg_rouge1 = sum([score["rouge1"].fmeasure for score in rouge_scores]) / len(rouge_scores)
avg_rouge2 = sum([score["rouge2"].fmeasure for score in rouge_scores]) / len(rouge_scores)
avg_rougeL = sum([score["rougeL"].fmeasure for score in rouge_scores]) / len(rouge_scores)

{
    "Average BLEU": round(avg_bleu, 4),
    "Average METEOR": round(avg_meteor, 4),
    "Average ROUGE-1": round(avg_rouge1, 4),
    "Average ROUGE-2": round(avg_rouge2, 4),
    "Average ROUGE-L": round(avg_rougeL, 4),
}



"""##Performance Metrics"""

pip install rouge-score nltk

from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score
from nltk.translate.bleu_score import sentence_bleu

"""###ROUGE"""

from rouge_score import rouge_scorer

rouge_scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)
rouge_scores = []

for ground_truth, generated_response in zip(df["Response"], df['Generated_Response']):
    scores = rouge_scorer.score(ground_truth, generated_response)
    rouge_scores.append(scores)

# Example to calculate average ROUGE-1 score
avg_rouge1 = sum([score["rouge1"].fmeasure for score in rouge_scores]) / len(rouge_scores)
print(f"Average ROUGE-1: {avg_rouge1:.4f}")

"""###BLUE"""

from nltk.translate.bleu_score import sentence_bleu

bleu_scores = []

for ground_truth, generated_response in zip(df["Response"], df['Generated_Response']):
    reference = ground_truth.split()
    candidate = generated_response.split()
    score = sentence_bleu([reference], candidate)
    bleu_scores.append(score)

avg_bleu = sum(bleu_scores) / len(bleu_scores)
print(f"Average BLEU: {avg_bleu:.4f}")

"""###METEOR"""

import nltk
nltk.download('wordnet')

from nltk.translate.meteor_score import meteor_score

meteor_scores = []

for ground_truth, generated_response in zip(df["Response"], df['Generated_Response']):
    meteor = meteor_score([ground_truth.split()], generated_response.split())
    meteor_scores.append(meteor)

avg_meteor = sum(meteor_scores) / len(meteor_scores)
print(f"Average METEOR: {avg_meteor:.4f}")



"""#Model using Inference API from Huggingface"""

from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("heyIamUmair/llama3-3b-merged-legal", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("heyIamUmair/llama3-3b-merged-legal")
prompt = "### Question:\nWhat is talaq under Pakistani law?\n\n### Answer:\n"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=150)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

import requests

API_URL = "https://api-inference.huggingface.co/models/heyIamUmair/llama3-3b-merged-legal"
headers = {"Authorization": "Bearer your_hf_token_here"}

response = requests.post(API_URL, headers=headers, json={"inputs": "What is FIR in Pakistan?"})
print(response.json())

"""#Downloading the model"""

from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("heyIamUmair/llama3-3b-merged-legal", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("heyIamUmair/llama3-3b-merged-legal")

model.save_pretrained("llama3_local")
tokenizer.save_pretrained("llama3_local")

print("✅ Model and tokenizer saved locally in llama3_local/")

import shutil

shutil.make_archive("llama3_local", 'zip', "llama3_local")
print("✅ Zipped the folder successfully!")

from google.colab import files
files.download("llama3_local.zip")

ls -lh llama3_local/*.safetensors